export const PRODUCT_GET_SUCC="PRODUCT_GET_SUCC"
export const PRODUCT_GET_INVENTERY="PRODUCT_GET_INVENTERY"
export const SET_FILTER_DATA="SET_FILTER_DATA"
export const SET_ASC_DATA="SET_ASC_DATA"
export const SET_SINGLE_PRODUCT="SET_SINGLE_PRODUCT"
export const ISLOADING="ISLOADING"
export const ISERROR="ISERROR"
export const DEALER="DEALER"

